//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce__projet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit
    {
        public int idproduit { get; set; }
        public string nom { get; set; }
        public Nullable<int> prix { get; set; }
        public Nullable<int> quantite { get; set; }
        public string image { get; set; }
        public string titre { get; set; }
    }
}
